apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: bi-analytics
spec:
  owner: team-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Metabase
  description: THG Metabase
  tags:
    - bi
    - analytics
  links:
    - url: http://thserver.corp.tonghuagroup.com:30030
      title: Metabase
      icon: web
spec:
  type: bi-analytics
  lifecycle: System
  owner: team-system
  system: bi-analytics
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
