apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: monitor
spec:
  owner: team-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Monitor
  description: THG Monitor
  tags:
    - monitor
    - webservice
  links:
    - url: http://grafana.corp.tonghuagroup.com:3000/login
      title: Grafana Internal
      icon: web
    - url: https://status.thamc.co.th
      title: Grafana thamstatus
      icon: web
    - url: http://192.168.99.4/cscc9160a2/mts/config/log_off_page.htm
      title: Destor Switch 3rd Floor
      icon: web
    - url: http://192.168.110.201:9090
      title: Prometheus Internal
      icon: web
spec:
  type: monitor
  lifecycle: System
  owner: team-system
  system: monitor
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
