apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: System-THL
  description: All infrastructure THL
  tags:
    - java
    - data
  links:
    - url: http://192.168.99.2/csb6652b71/config/log_off_page.htm
      title: Switch Server Room(3rd Floor)
      icon: web
    - url: https://example.com/group
      title: Example Group
      icon: web
    - url: http://192.168.99.4/cscc9160a2/mts/config/log_off_page.htm
      title: Destor Switch 3rd Floor
      icon: web
    - url: https://192.168.98.188/62f01f71b6d948019d13ac8cb34971b3/login
      title: Controller
      icon: web
    - url: https://example.com/help
      title: Support
      icon: web
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: web
  annotations:
    backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
spec:
  type: service
  lifecycle: experimental
  owner: System-Teams
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
