apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Synology-Nas
  description: Synology Nas Tonghuagroup
  tags:
    - service
    - nas
    - storage
  links:
    - url: https://th877.corp.tonghuagroup.com/
      title: FileShare
      icon: web
    - url: https://th881.corp.tonghuagroup.com/
      title: Backup Server
      icon: web
    - url: https://drive.tonghuagroup.com/
      title: Synology Drive
      icon: web
    - url: https://audio.corp.tonghuagroup.com/
      title: Audio 
      icon: dashboard
    - url: https://file.corp.tonghuagroup.com/
      title: File
      icon: file
    - url: https://photo.corp.tonghuagroup.com/
      title: Photo
      icon: photo
    - url: https://video.corp.tonghuagroup.com/
      title: video
      icon: video
  annotations:
    backstage.io/managed-by-location: url: https://coda.io/d/Company-Servers-Applications-and-Services_dqSD72odWEj/Synology-NAS_surOZ#_luwqH
spec:
  type: Web Service
  lifecycle: System
  owner: team-system
  system: system
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
