apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Synology-Nas
  description: Synology Nas Tonghuagroup
  tags:
    - service
    - nas
    - storage
  links:
    - url: https://th877.corp.tonghuagroup.com/
      title: FileShare
      icon: web
    - url: https://th881.corp.tonghuagroup.com/
      title: Backup Server
      icon: web
    - url: https://drive.tonghuagroup.com/
      title: Synology Drive
      icon: web
    - url: https://audio.corp.tonghuagroup.com/
      title: Audio 
      icon: audio
    - url: https://file.corp.tonghuagroup.com/
      title: File
      icon: file
    - url: https://photo.corp.tonghuagroup.com/
      title: Photo
      icon: photo
    - url: https://video.corp.tonghuagroup.com/
      title: video
      icon: video
  #annotations:
    #backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
spec:
  type: Web Service
  lifecycle: System
  owner: System-Teams
  system: System Infrastructure Portals
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
